name: Build packages

on:
  pull_request:
  push:
  workflow_run:
    workflows: ["flake-update"]

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.mat.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: frai3nix
          pushFilter: '(-source$ | nixpkgs\.tar\.gz$)'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check
      - id: mat
        run: |
          MATRIX=$(nix flake show --json | jq -c '
            .packages
            | to_entries
            | map(
                .key as $system
                | .value
                | keys[]
                | {
                    name: .,
                    system: $system,
                    os: (
                      if $system == "x86_64-linux" then "ubuntu-latest"
                      elif $system == "aarch64-linux" then "ubuntu-latest-24.04-arm"
                      elif $system == "x86_64-darwin" then "macos-15-intel"
                      elif $system == "aarch64-darwin" then "macos-latest"
                      else empty
                      end
                    ),
                    attr: "packages.\($system).\(. )"
                  }
              )
          ')

          echo "matrix={\"include\":$MATRIX}"
          echo "matrix={\"include\":$MATRIX}" >> "$GITHUB_OUTPUT"

  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: frai3nix
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build -L '.#${{ matrix.attr }}'
